### ISSUE TITLE
shield not starting error exios.js

### ISSUE THREAD

**Issue by SmOkEnksp** [muon-protocol/light-shield-node#1]
nodejs server.js
/path/to/muon-shield/light-shield-node/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/sdb/muon-shield/light-shield-node/server.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by bakhshandeh** [comment]
Maybe your node version is too old. Try using version 16 or higher.

```bash
$ node --version
v16.19.0
```

**Comment by SmOkEnksp** [comment]
> Maybe your node version is too old. Try using version 16 or higher.
> 
> ```shell
> $ node --version
> v16.19.0
> ```

node -v
v18.16.0
 i try 16 and 18 and 20 node versions. its the same.
